### ISSUE TITLE
ImportError: cannot import name 'prroi_pool2d' 

### ISSUE THREAD

**Issue by shang153284** [ZikunZhou/SAOT#6]
Traceback (most recent call last):
  File "test_saot_fs.py", line 252, in <module>
    main(args.run_id)
  File "test_saot_fs.py", line 53, in main
    config_tracker = Tracker(args.tracker_name, args.tracker_param, run_id=run_id, dataset_name=args.dataset)
  File "../pytracking/evaluation/tracker.py", line 76, in __init__
    tracker_module = importlib.import_module('pytracking.tracker.{}'.format(self.name))
  File "/home/shangyj/anaconda3/envs/SAOT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../pytracking/tracker/saot/__init__.py", line 1, in <module>
    from .saot import SAOT
  File "../pytracking/tracker/saot/saot.py", line 15, in <module>
    from ltr.external.PreciseRoIPooling.pytorch.prroi_pool import prroi_pool2d
ImportError: cannot import name 'prroi_pool2d' from 'ltr.external.PreciseRoIPooling.pytorch.prroi_pool' (../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/__init__.py)
(SAOT) shangyj@shangyj:~/Desktop/SAOT/pytracking$ python test_saot_fs.py saot saot_otb --dataset OTB100
Traceback (most recent call last):
  File "test_saot_fs.py", line 252, in <module>
    main(args.run_id)
  File "test_saot_fs.py", line 53, in main
    config_tracker = Tracker(args.tracker_name, args.tracker_param, run_id=run_id, dataset_name=args.dataset)
  File "../pytracking/evaluation/tracker.py", line 76, in __init__
    tracker_module = importlib.import_module('pytracking.tracker.{}'.format(self.name))
  File "/home/shangyj/anaconda3/envs/SAOT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../pytracking/tracker/saot/__init__.py", line 1, in <module>
    from .saot import SAOT
  File "../pytracking/tracker/saot/saot.py", line 15, in <module>
    from ltr.external.PreciseRoIPooling.pytorch.prroi_pool import prroi_pool2d
ImportError: cannot import name 'prroi_pool2d' from 'ltr.external.PreciseRoIPooling.pytorch.prroi_pool' (../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/__init__.py)

**Comment by shang153284** [comment]
12/5000 
Excuse me, what is going on here?

**Comment by shang153284** [comment]
12/5000 
Excuse me, what is going on here?
