### ISSUE TITLE
TypeError: replication_pad2d(): argument 'padding' must be tuple of ints, but found element of type float at pos 1

### ISSUE THREAD

**Issue by shang153284** [ZikunZhou/SAOT#7]
Traceback (most recent call last):
  File "test_saot_fs.py", line 252, in <module>
    main(args.run_id)
  File "test_saot_fs.py", line 179, in main
    tracker.track_pysot_initialize(img, gt_bbox_, video.name)
  File "../pytracking/tracker/base/basetracker.py", line 23, in track_pysot_initialize
    self.initialize(image, {'init_bbox': init_state, 'video_name': video_name})
  File "../pytracking/tracker/saot/saot.py", line 93, in initialize
    init_backbone_feat = self.generate_init_samples(im)
  File "../pytracking/tracker/saot/saot.py", line 409, in generate_init_samples
    im_patches = sample_patch_transformed(im, self.init_sample_pos, self.init_sample_scale, aug_expansion_sz, self.transforms)
  File "../pytracking/features/preprocessing.py", line 25, in sample_patch_transformed
    im_patch, _ = sample_patch(im, pos, scale*image_sz, image_sz, is_mask=is_mask)
  File "../pytracking/features/preprocessing.py", line 129, in sample_patch
    im_patch = F.pad(im2, (-tl[1].item(), br[1].item() - im2.shape[3], -tl[0].item(), br[0].item() - im2.shape[2]), pad_mode)
  File "/home/shangyj/anaconda3/envs/SAOT/lib/python3.7/site-packages/torch/nn/functional.py", line 3572, in _pad
    return torch._C._nn.replication_pad2d(input, pad)
TypeError: replication_pad2d(): argument 'padding' must be tuple of ints, but found element of type float at pos 1

**Comment by shang153284** [comment]
hello，Thank you for your code, may I ask how to deal with this situation
